#!/bin/bash
# lib/brew.sh — Dynamic Brewfile generator and package management engine.

# Prevent multiple inclusions
if [ -n "${_MACOS_SETUP_BREW_LOADED:-}" ]; then
    return 0
fi
_MACOS_SETUP_BREW_LOADED=1

# Check if an item is present in a space-delimited list
_is_in_list() {
    local item="$1" list="$2"
    for el in $list; do
        if [ "$el" = "$item" ]; then
            return 0
        fi
    done
    return 1
}

# Generate a tailored Brewfile according to active categories & exclusions
generate_brewfile() {
    local output_file="$1"
    mkdir -p "$(dirname "$output_file")"

    cat <<'EOF' >"$output_file"
# Dynamically generated by macos-setup
EOF

    # 1. TAPS
    echo "" >>"$output_file"
    echo "# --- TAPS ---" >>"$output_file"
    [ "$CAT_MOBILE" -eq 1 ] && echo 'tap "leoafarias/fvm"' >>"$output_file"
    [ "$CAT_CUSTOM_TAP" -eq 1 ] && echo 'tap "jcyrus/tap"' >>"$output_file"
    [ "$CAT_WINDOW_MANAGEMENT" -eq 1 ] && echo 'tap "nikitabobko/tap"' >>"$output_file"
    [ "$CAT_WINDOW_MANAGEMENT" -eq 1 ] && echo 'tap "FelixKratz/formulae"' >>"$output_file"

    # Helper function to append package if not skipped
    _add_brew() {
        local pkg="$1"
        if ! _is_in_list "$pkg" "$SKIPPED_FORMULAE"; then
            echo "brew \"$pkg\"" >>"$output_file"
        fi
    }

    _add_cask() {
        local pkg="$1"
        if ! _is_in_list "$pkg" "$SKIPPED_CASKS"; then
            echo "cask \"$pkg\"" >>"$output_file"
        fi
    }

    # 2. WINDOW MANAGEMENT
    if [ "$CAT_WINDOW_MANAGEMENT" -eq 1 ]; then
        echo "" >>"$output_file"
        echo "# --- WINDOW MANAGEMENT ---" >>"$output_file"
        _add_cask "aerospace"
        _add_brew "borders"
    fi

    # 3. TERMINAL
    if [ "$CAT_TERMINAL" -eq 1 ]; then
        echo "" >>"$output_file"
        echo "# --- TERMINAL ---" >>"$output_file"
        _add_cask "ghostty"
        _add_brew "starship"
        _add_brew "zoxide"
        _add_brew "tmux"
    fi

    # 4. CORE CLI
    if [ "$CAT_CORE_CLI" -eq 1 ]; then
        echo "" >>"$output_file"
        echo "# --- CORE CLI ---" >>"$output_file"
        _add_brew "git"
        _add_brew "gh"
        _add_brew "eza"
        _add_brew "bat"
        _add_brew "ripgrep"
        _add_brew "fd"
        _add_brew "fzf"
        _add_brew "jq"
        _add_brew "tealdeer"
        _add_brew "mas"
    fi

    # 5. MODERN CLI
    if [ "$CAT_MODERN_CLI" -eq 1 ]; then
        echo "" >>"$output_file"
        echo "# --- MODERN CLI ---" >>"$output_file"
        _add_brew "git-delta"
        _add_brew "dust"
        _add_brew "duf"
        _add_brew "procs"
        _add_brew "btop"
        _add_brew "hyperfine"
        _add_brew "tokei"
        _add_brew "yazi"
        _add_brew "tree-sitter"
    fi

    # 6. SHELL QUALITY
    if [ "$CAT_SHELL_QUALITY" -eq 1 ]; then
        echo "" >>"$output_file"
        echo "# --- SHELL QUALITY ---" >>"$output_file"
        _add_brew "shellcheck"
        _add_brew "shfmt"
        _add_brew "lefthook"
    fi

    # 7. AI / LLM
    if [ "$CAT_AI" -eq 1 ]; then
        echo "" >>"$output_file"
        echo "# --- AI / LLM ---" >>"$output_file"
        _add_brew "ollama"
    fi

    # 8. EDITORS
    if [ "$CAT_EDITORS" -eq 1 ]; then
        echo "" >>"$output_file"
        echo "# --- EDITORS ---" >>"$output_file"
        _add_brew "neovim"
        _add_cask "visual-studio-code"
    fi

    # 9. GIT TUIs
    if [ "$CAT_GIT_TUIS" -eq 1 ]; then
        echo "" >>"$output_file"
        echo "# --- GIT TUIs ---" >>"$output_file"
        _add_brew "lazygit"
        _add_brew "lazydocker"
    fi

    # 10. RUST
    if [ "$CAT_RUST" -eq 1 ]; then
        echo "" >>"$output_file"
        echo "# --- RUST ---" >>"$output_file"
        _add_brew "rustup"
        _add_brew "bacon"
        _add_brew "cargo-binstall"
    fi

    # 11. WEB
    if [ "$CAT_WEB" -eq 1 ]; then
        echo "" >>"$output_file"
        echo "# --- WEB ---" >>"$output_file"
        _add_brew "fnm"
        _add_brew "pnpm"
    fi

    # 12. MOBILE
    if [ "$CAT_MOBILE" -eq 1 ]; then
        echo "" >>"$output_file"
        echo "# --- MOBILE ---" >>"$output_file"
        _add_brew "leoafarias/fvm/fvm"
        _add_brew "cocoapods"
        _add_brew "scrcpy"
    fi

    # 13. BROWSERS
    if [ "$CAT_BROWSERS" -eq 1 ] && [ -n "${CONFIG_BROWSERS:-}" ]; then
        echo "" >>"$output_file"
        echo "# --- BROWSERS ---" >>"$output_file"
        for browser in $CONFIG_BROWSERS; do
            _add_cask "$browser"
        done
    fi

    # 14. GUI CORE
    if [ "$CAT_GUI_CORE" -eq 1 ]; then
        echo "" >>"$output_file"
        echo "# --- GUI APPS ---" >>"$output_file"
        _add_cask "raycast"
        _add_cask "orbstack"
        _add_cask "tableplus"
        _add_cask "shottr"
        _add_cask "bruno"
        _add_cask "obsidian"
        _add_cask "appcleaner"
        _add_cask "the-unarchiver"
        _add_cask "hiddenbar"
        _add_cask "stats"
        _add_cask "utm"
        _add_cask "sf-symbols"
    fi

    # 15. FONTS
    if [ "$CAT_FONTS" -eq 1 ]; then
        echo "" >>"$output_file"
        echo "# --- FONTS ---" >>"$output_file"
        _add_cask "font-0xproto-nerd-font"
        _add_cask "font-jetbrains-mono-nerd-font"
    fi

    # 16. SECURITY
    if [ "$CAT_SECURITY" -eq 1 ]; then
        echo "" >>"$output_file"
        echo "# --- SECURITY ---" >>"$output_file"
        _add_cask "bitwarden"
        _add_cask "tailscale-app"
    fi

    # 17. CREATIVE / MEDIA
    if [ "$CAT_CREATIVE" -eq 1 ]; then
        echo "" >>"$output_file"
        echo "# --- CREATIVE / LIFESTYLE ---" >>"$output_file"
        _add_cask "figma"
        _add_brew "imagemagick"
        _add_cask "telegram"
        _add_cask "spotify"
        _add_cask "iina"
        _add_cask "stremio"
    fi

    # 18. CUSTOM TAP APPS
    if [ "$CAT_CUSTOM_TAP" -eq 1 ]; then
        echo "" >>"$output_file"
        echo "# --- CUSTOM TAP APPS ---" >>"$output_file"
        _add_brew "jcyrus/tap/zerodrop"
        _add_brew "jcyrus/tap/spektr"
    fi
}

# Install Homebrew if missing and update
bootstrap_homebrew() {
    if ! command -v brew &>/dev/null; then
        log_info "Installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        if [ -d "/opt/homebrew/bin" ]; then
            eval "$(/opt/homebrew/bin/brew shellenv)"
        elif [ -d "/usr/local/bin" ]; then
            eval "$(/usr/local/bin/brew shellenv)"
        fi
    else
        log_info "Homebrew found. Updating..."
        brew update
    fi
}

# Trust custom taps for Homebrew 6+
trust_taps() {
    if brew trust --help &>/dev/null; then
        [ "$CAT_CUSTOM_TAP" -eq 1 ] && brew trust jcyrus/tap 2>/dev/null || true
        [ "$CAT_MOBILE" -eq 1 ] && brew trust leoafarias/fvm 2>/dev/null || true
        [ "$CAT_WINDOW_MANAGEMENT" -eq 1 ] && brew trust nikitabobko/tap 2>/dev/null || true
        [ "$CAT_WINDOW_MANAGEMENT" -eq 1 ] && brew trust FelixKratz/formulae 2>/dev/null || true
    fi
}

# Execute dynamic brew bundle
install_brew_packages() {
    local brewfile="$1"
    if [ ! -f "$brewfile" ]; then
        log_error "Generated Brewfile not found: $brewfile"
        return 1
    fi

    log_step "Installing apps and CLI tools from generated manifest..."
    trust_taps

    if ! brew bundle --file="$brewfile"; then
        log_warn "Some Brewfile entries failed to install. Continuing with setup."
        log_dim "Re-run 'brew bundle --file=$brewfile' afterwards to retry."
        return 0
    fi
    log_success "All packages installed cleanly."
}
